AWSTemplateFormatVersion: '2010-09-09'
Description: AWS SAM CLI Nested Stack for Auto Dependency Layer Creation
Metadata:
  SamCliInfo: 1.116.0
  key: AWS SAM CLI sync command
Outputs:
  SimpleCRUDApp3d45fd95DepLayer:
    Value:
      Ref: SimpleCRUDApp3d45fd95DepLayer
Resources:
  SimpleCRUDApp3d45fd95DepLayer:
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      CompatibleRuntimes:
      - java17
      ContentUri: C:\aws\simple-crud-serverless\.aws-sam\auto-dependency-layer\SimpleCRUDApp3d45fd95DepLayer
      Description: Auto created layer for dependencies of function SimpleCRUDApp
      LayerName: simple-crud-serv7d4d68a9-SimpleCRUDApp3d45fd95-DepLayer
      RetentionPolicy: Delete
    Type: AWS::Serverless::LayerVersion
Transform: AWS::Serverless-2016-10-31
